In [1]:
import pandas as pd

In [3]:
air_quality_df = pd.read_parquet("../data/raw/delhi_raw.parquet")
weather_df = pd.read_parquet("../data/external/weather.parquet")
industrial_df = pd.read_parquet("../data/external/industrial.parquet")

In [4]:
air_quality_df.head()

,date,location_id,location_name,latitude,longitude,parameter,unit,value
0,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,co,µg/m³,1200.0
1,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,no2,µg/m³,28.9
2,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,o3,µg/m³,20.5
3,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,pm10,µg/m³,295.0
4,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,pm25,µg/m³,199.0

In [5]:
weather_df.head()

,date,location_name,latitude,longitude,temperature,wind_speed,wind_direction,precipitation,humidity,boundary_layer_height
0,2021-12-31,"Delhi Technological University, Delhi - CPCB",28.744,77.12,10.837501,8.647496,285.962738,0.000000,92.428314,1.965647
1,2022-01-01,"Delhi Technological University, Delhi - CPCB",28.744,77.12,11.631249,10.028439,296.840424,0.000000,79.554359,1.935728
2,2022-01-02,"Delhi Technological University, Delhi - CPCB",28.744,77.12,12.306251,10.594036,284.281097,0.000000,80.146652,2.124942
3,2022-01-03,"Delhi Technological University, Delhi - CPCB",28.744,77.12,14.158334,8.913181,292.720032,0.100000,78.377739,1.983000
4,2022-01-04,"Delhi Technological University, Delhi - CPCB",28.744,77.12,13.412499,18.079027,115.164062,9.800001,73.822693,0.668925

In [6]:
industrial_df.head()

            name  latitude  longitude  capacity_mw primary_fuel
0       BADARPUR   28.5060    77.3066      705.000         Coal
1  DADRI (NCTPP)   28.6030    77.6078     1820.000         Coal
2       DADRI GT   28.5932    77.6101      829.780          Gas
3     F_BAD CCGT   28.3452    77.3615      431.586          Gas
4       H_GANJ B   28.0179    78.1326      605.000         Coal