In [7]:
import pandas as pd

In [8]:
air_quality_df = pd.read_parquet("../data/raw/delhi_raw.parquet")
weather_df = pd.read_parquet("../data/external/weather.parquet")
industrial_df = pd.read_parquet("../data/external/industrial.parquet")

In [9]:
air_quality_df.head()

,date,location_id,location_name,latitude,longitude,parameter,unit,value
0,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,co,µg/m³,1200.0
1,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,no2,µg/m³,28.9
2,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,o3,µg/m³,20.5
3,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,pm10,µg/m³,295.0
4,2022-01-01,6932,"Alipur, Delhi - DPCC",28.815329,77.15301,pm25,µg/m³,199.0

In [10]:
weather_df.head()

,date,location_name,latitude,longitude,temperature,wind_speed,wind_direction,precipitation,humidity,boundary_layer_height
0,2021-12-31,Air Check,28.623056,77.234167,10.993751,9.114471,288.245911,0.000000,92.912697,1.987685
1,2022-01-01,Air Check,28.623056,77.234167,11.706250,8.714677,296.672424,0.000000,78.775581,1.921755
2,2022-01-02,Air Check,28.623056,77.234167,12.314583,10.308831,288.294586,0.000000,80.281754,2.136342
3,2022-01-03,Air Check,28.623056,77.234167,14.054165,9.504273,297.226715,0.000000,78.129021,2.042342
4,2022-01-04,Air Check,28.623056,77.234167,13.302085,19.453327,116.991753,9.000002,72.767830,0.614268

In [11]:
industrial_df.head()

            name  latitude  longitude  capacity_mw primary_fuel
0       BADARPUR   28.5060    77.3066      705.000         Coal
1  DADRI (NCTPP)   28.6030    77.6078     1820.000         Coal
2       DADRI GT   28.5932    77.6101      829.780          Gas
3     F_BAD CCGT   28.3452    77.3615      431.586          Gas
4       H_GANJ B   28.0179    78.1326      605.000         Coal

In [12]:
air_cleaned_df = pd.read_parquet("../data/cleaned/air_quality.parquet")

In [13]:
air_cleaned_df.head()

,date,location_id,location_name,latitude,longitude,parameter,unit,value,exceeds_who,who_threshold,is_suspicious
0,2022-01-01,301,"Vikas Sadan, Gurugram - HSPCB",28.450124,77.026305,co,µg/m³,1780.0,False,4000.0,False
1,2022-01-01,301,"Vikas Sadan, Gurugram - HSPCB",28.450124,77.026305,no2,µg/m³,60.2,True,25.0,False
2,2022-01-01,301,"Vikas Sadan, Gurugram - HSPCB",28.450124,77.026305,o3,µg/m³,63.8,False,100.0,False
3,2022-01-01,301,"Vikas Sadan, Gurugram - HSPCB",28.450124,77.026305,pm25,µg/m³,226.0,True,15.0,False
4,2022-01-01,301,"Vikas Sadan, Gurugram - HSPCB",28.450124,77.026305,so2,µg/m³,11.3,False,40.0,False